actors:
  komatatsu:
    image_url: /images/actors/komatatsu.png
    name: komatatsu
    url: https://twitter.com/k0matatsu
  mhidaka:
    image_url: /images/actors/mhidaka.jpg
    name: mhidaka
    url: https://twitter.com/mhidaka
  laco2:
    image_url: /images/actors/laco.jpg
    name: laco2
    url: https://twitter.com/laco2net
  yokoma:
    image_url: /images/actors/yokoma.jpg
    name: KeithYokoma
    url: https://twitter.com/KeithYokoma
  corocn:
    image_url: /images/actors/corocn.jpg
    name: ころちゃん
    url: https://twitter.com/corocn
  kirimin:
    image_url: /images/actors/kirimin.png
    name: きりみんちゃん
    url: https://kirimin-chan.site/
  fukuiretu:
    image_url: /images/actors/fukuiretu.jpg
    name: fukuiretu
    url: https://twitter.com/fukuiretu
author: komatatsu
description: 田舎から配信してます
description_long: 田舎でリモートワークをしているAndroidエンジニアが配信しているpodcastです。ゲスト出演してくれる人をいつだって募集中、出演したいぞ〜という人は<a href=https://twitter.com/inaka_fm>@inaka_fm</a>にメンションしてくれよな！！
email:
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
google_analytics: UA-116775910-1
hashtag: 田舎fm
itunes_podcast_url:
keywords:
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 田舎.fm
url: https://komatatsu.github.io/inaka-fm/
